all: 
	echo "try make install as root"

install:
	cp openvpn-pygtktray.py /usr/local/bin/openvpn-pgtray
	cp ovpntech_key_green.png /usr/share/icons/hicolor/48x48/ovpntech_key_green.png

uninstall: 
	rm /usr/local/bin/openvpn-pgtray
	rm /usr/share/icons/hicolor/48x48/ovpntech_key_green.png
